-- WVP-PRO-GO PostgreSQL Schema
-- Auto-generated from Java WVP-PRO v2.7.4

CREATE TABLE IF NOT EXISTS wvp_device (
    id SERIAL PRIMARY KEY,
    device_id VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255),
    manufacturer VARCHAR(255),
    model VARCHAR(255),
    firmware VARCHAR(255),
    transport VARCHAR(50),
    stream_mode VARCHAR(50),
    on_line BOOLEAN DEFAULT FALSE,
    ip VARCHAR(50),
    port INTEGER,
    expires INTEGER,
    host_address VARCHAR(50),
    charset VARCHAR(50),
    ssrc_check BOOLEAN DEFAULT FALSE,
    geo_coord_sys VARCHAR(50),
    media_server_id VARCHAR(50) DEFAULT 'auto',
    custom_name VARCHAR(255),
    sdp_ip VARCHAR(50),
    local_ip VARCHAR(50),
    password VARCHAR(255),
    as_message_channel BOOLEAN DEFAULT FALSE,
    heart_beat_interval INTEGER,
    heart_beat_count INTEGER,
    position_capability INTEGER,
    channel_count INTEGER,
    subscribe_cycle_for_catalog INTEGER DEFAULT 0,
    subscribe_cycle_for_mobile_position INTEGER DEFAULT 0,
    mobile_position_submission_interval INTEGER DEFAULT 5,
    subscribe_cycle_for_alarm INTEGER DEFAULT 0,
    broadcast_push_after_ack BOOLEAN DEFAULT FALSE,
    server_id VARCHAR(50),
    create_time VARCHAR(50),
    update_time VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS wvp_device_channel (
    id SERIAL PRIMARY KEY,
    gb_id SERIAL,
    device_id VARCHAR(50),
    name VARCHAR(255),
    gb_device_id VARCHAR(50),
    gb_name VARCHAR(255),
    gb_manufacturer VARCHAR(50),
    gb_model VARCHAR(50),
    gb_owner VARCHAR(50),
    gb_civil_code VARCHAR(50),
    gb_block VARCHAR(50),
    gb_address VARCHAR(50),
    gb_parental INTEGER,
    gb_parent_id VARCHAR(50),
    gb_safety_way INTEGER,
    gb_register_way INTEGER,
    gb_cert_num VARCHAR(50),
    gb_certifiable INTEGER,
    gb_err_code INTEGER,
    gb_end_time VARCHAR(50),
    gb_secrecy INTEGER,
    gb_ip_address VARCHAR(50),
    gb_port INTEGER,
    gb_password VARCHAR(255),
    gb_status VARCHAR(50),
    gb_longitude DOUBLE PRECISION,
    gb_latitude DOUBLE PRECISION,
    gps_altitude DOUBLE PRECISION,
    gps_speed DOUBLE PRECISION,
    gps_direction DOUBLE PRECISION,
    gps_time VARCHAR(50),
    gb_business_group_id VARCHAR(50),
    gb_ptz_type INTEGER,
    gb_position_type INTEGER,
    gb_room_type INTEGER,
    gb_use_type INTEGER,
    gb_supply_light_type INTEGER,
    gb_direction_type INTEGER,
    gb_resolution VARCHAR(50),
    gb_download_speed VARCHAR(50),
    gb_svc_space_support_mod INTEGER,
    gb_svc_time_support_mode INTEGER,
    record_plan VARCHAR(50),
    data_type INTEGER DEFAULT 1,
    data_device_id INTEGER,
    stream_identification VARCHAR(50),
    enable_broadcast INTEGER DEFAULT 0,
    map_level INTEGER DEFAULT 0,
    parental INTEGER,
    parent_id VARCHAR(50),
    safety_way INTEGER,
    register_way INTEGER,
    cert_num VARCHAR(50),
    certifiable INTEGER,
    err_code INTEGER,
    end_time VARCHAR(50),
    secrecy INTEGER,
    ip_address VARCHAR(50),
    port INTEGER,
    password VARCHAR(255),
    status VARCHAR(50),
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    ptz_type INTEGER,
    position_type INTEGER,
    room_type INTEGER,
    use_type INTEGER,
    supply_light_type INTEGER,
    direction_type INTEGER,
    resolution VARCHAR(50),
    manufacturer VARCHAR(50),
    model VARCHAR(50),
    owner VARCHAR(50),
    civil_code VARCHAR(50),
    block VARCHAR(50),
    address VARCHAR(50),
    stream_id VARCHAR(50)
);
CREATE INDEX idx_device_channel_device_id ON wvp_device_channel(device_id);

CREATE TABLE IF NOT EXISTS wvp_platform (
    id SERIAL PRIMARY KEY,
    enable INTEGER DEFAULT 0,
    name VARCHAR(255),
    server_gb_id VARCHAR(50) UNIQUE,
    server_gb_domain VARCHAR(50),
    server_ip VARCHAR(50),
    server_port INTEGER,
    device_gb_id VARCHAR(50),
    device_ip VARCHAR(50),
    device_port INTEGER,
    username VARCHAR(255),
    password VARCHAR(255),
    expires INTEGER,
    keep_timeout INTEGER,
    transport VARCHAR(50),
    character_set VARCHAR(50),
    ptz INTEGER,
    rtcp INTEGER,
    status VARCHAR(50),
    channel_count INTEGER,
    catalog_subscribe INTEGER,
    alarm_subscribe INTEGER,
    mobile_position_subscribe INTEGER,
    catalog_group INTEGER,
    as_message_channel BOOLEAN DEFAULT FALSE,
    send_stream_ip VARCHAR(50),
    auto_push_channel BOOLEAN DEFAULT FALSE,
    catalog_with_platform INTEGER,
    catalog_with_group INTEGER,
    catalog_with_region INTEGER,
    civil_code VARCHAR(50),
    manufacturer VARCHAR(255),
    model VARCHAR(255),
    address VARCHAR(255),
    register_way INTEGER,
    secrecy INTEGER,
    server_id VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS wvp_common_group (
    id SERIAL PRIMARY KEY,
    device_id VARCHAR(50) UNIQUE,
    name VARCHAR(255),
    parent_id BIGINT,
    parent_device_id VARCHAR(50),
    business_group VARCHAR(50),
    civil_code VARCHAR(50),
    alias VARCHAR(255),
    create_time VARCHAR(50),
    update_time VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS wvp_common_region (
    id SERIAL PRIMARY KEY,
    device_id VARCHAR(50) UNIQUE,
    name VARCHAR(255),
    parent_id BIGINT,
    parent_device_id VARCHAR(50),
    create_time VARCHAR(50),
    update_time VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS wvp_stream_proxy (
    id SERIAL PRIMARY KEY,
    type INTEGER,
    app VARCHAR(255),
    stream VARCHAR(255),
    url VARCHAR(255),
    ffmpeg_cmd TEXT,
    enable_audio BOOLEAN,
    enable_mp4 BOOLEAN,
    enable BOOLEAN,
    timeout INTEGER,
    pulling BOOLEAN,
    enable_remove_key BOOLEAN,
    remove_key VARCHAR(255),
    media_server_id VARCHAR(50),
    channel_id BIGINT,
    device_id VARCHAR(50),
    name VARCHAR(255),
    description VARCHAR(255),
    create_time VARCHAR(50),
    update_time VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS wvp_stream_push (
    id SERIAL PRIMARY KEY,
    app VARCHAR(255),
    stream VARCHAR(255),
    total_origin INTEGER,
    enable_audio BOOLEAN,
    enable_mp4 BOOLEAN,
    pushing BOOLEAN,
    media_server_id VARCHAR(50),
    channel_id BIGINT,
    device_id VARCHAR(50),
    name VARCHAR(255),
    description VARCHAR(255),
    create_time VARCHAR(50),
    update_time VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS wvp_media_server (
    id VARCHAR(50) PRIMARY KEY,
    ip VARCHAR(50),
    hook_ip VARCHAR(50),
    sdp_ip VARCHAR(50),
    stream_ip VARCHAR(50),
    http_port INTEGER,
    http_ssl_port INTEGER,
    rtmp_port INTEGER,
    rtmp_ssl_port INTEGER,
    flv_port INTEGER,
    flv_ssl_port INTEGER,
    mp4_port INTEGER,
    ws_flv_port INTEGER,
    ws_flv_ssl_port INTEGER,
    rtsp_port INTEGER,
    rtsp_ssl_port INTEGER,
    rtp_proxy_port INTEGER,
    jtt_proxy_port INTEGER,
    auto_config BOOLEAN,
    secret VARCHAR(255),
    hook_alive_interval DOUBLE PRECISION,
    rtp_enable BOOLEAN,
    status BOOLEAN,
    rtp_port_range VARCHAR(50),
    send_rtp_port_range VARCHAR(50),
    record_assist_port INTEGER,
    default_server BOOLEAN,
    record_day INTEGER,
    record_path VARCHAR(255),
    type VARCHAR(50),
    transcode_suffix VARCHAR(50),
    server_id VARCHAR(50),
    create_time VARCHAR(50),
    update_time VARCHAR(50),
    last_keepalive_time VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS wvp_device_mobile_position (
    id SERIAL PRIMARY KEY,
    device_id VARCHAR(50) NOT NULL,
    channel_id VARCHAR(50) NOT NULL,
    device_name VARCHAR(255),
    time VARCHAR(50),
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    altitude DOUBLE PRECISION,
    speed DOUBLE PRECISION,
    direction DOUBLE PRECISION,
    report_source VARCHAR(50),
    create_time VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS wvp_device_alarm (
    id SERIAL PRIMARY KEY,
    device_id VARCHAR(50) NOT NULL,
    channel_id VARCHAR(50) NOT NULL,
    alarm_priority VARCHAR(50),
    alarm_method VARCHAR(50),
    alarm_time VARCHAR(50),
    alarm_description VARCHAR(255),
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    alarm_type VARCHAR(50),
    create_time VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS wvp_jt_terminal (
    id SERIAL PRIMARY KEY,
    phone_number VARCHAR(20) NOT NULL UNIQUE,
    plate_number VARCHAR(20),
    plate_color INTEGER,
    sim_card_id VARCHAR(20),
    terminal_id VARCHAR(20),
    terminal_model VARCHAR(20),
    manufacturer_id VARCHAR(20),
    province_id INTEGER,
    city_id INTEGER,
    online BOOLEAN DEFAULT FALSE,
    media_server_id VARCHAR(50),
    create_time VARCHAR(50),
    update_time VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS wvp_jt_channel (
    id SERIAL PRIMARY KEY,
    phone_number VARCHAR(20) NOT NULL,
    channel_id VARCHAR(20) NOT NULL,
    channel_name VARCHAR(255),
    channel_type INTEGER
);

CREATE TABLE IF NOT EXISTS wvp_user (
    id SERIAL PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    phone VARCHAR(20),
    email VARCHAR(255),
    enable BOOLEAN DEFAULT TRUE,
    create_time VARCHAR(50),
    update_time VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS wvp_user_role (
    id SERIAL PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE,
    description VARCHAR(255),
    create_time VARCHAR(50),
    update_time VARCHAR(50)
);
